CREATE DATABASE test;
DROP DATABASE test;
CREATE DATABASE record_company;
USE record_company;
CREATE TABLE test_table (test_column INT);
ALTER TABLE test_table ADD another_column VARCHAR(255);
DROP TABLE test_table;
CREATE TABLE bands (ID INT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE albums (ID INT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, release_year INT, band_id INT NOT NULL, PRIMARY KEY (ID), FOREIGN KEY (band_id) REFERENCES bands(ID));
INSERT INTO bands (name) VALUES ('Iron Maiden');
INSERT INTO bands (name) VALUES ('Deuce'), ('Avenged Sevenfold'), ('Ankor');
SELECT * FROM bands;
SELECT * FROM bands LIMIT 2;
SELECT name FROM bands;
SELECT ID AS ID, name AS band_name FROM bands;
SELECT * FROM bands ORDER BY name;
SELECT * FROM bands ORDER BY name DESC;
INSERT INTO albums (name, release_year, band_id) VALUES ('The Number Of The Beast', 1985, 1), ('Powerslave', 1984, 1), ('Nightmare', 2018, 2), ('Nightmare', 2010, 3), ('Test Album', NULL, 3);
SELECT * FROM albums;
SELECT name FROM albums;
SELECT DISTINCT name FROM albums;
UPDATE albums SET release_year = 1982 WHERE ID = 1;
SELECT * FROM albums WHERE release_year < 2000;
SELECT * FROM albums WHERE name LIKE '%er%';
SELECT * FROM albums WHERE name LIKE '%er%' OR band_id = 2;
SELECT * FROM albums WHERE release_year = 1984 AND band_id = 1;
SELECT * FROM albums WHERE release_year BETWEEN 2000 AND 2018;
SELECT * FROM albums WHERE release_year IS NULL;
DELETE FROM albums WHERE ID = 5;
SELECT * FROM bands JOIN albums ON bands.ID = albums.band_id;
SELECT * FROM bands INNER JOIN albums ON bands.ID = albums.band_id;
SELECT * FROM bands LEFT JOIN albums ON bands.ID = albums.band_id;
SELECT * FROM albums RIGHT JOIN bands ON albums.band_id = bands.ID;
SELECT AVG(release_year) FROM albums;
SELECT SUM(release_year) FROM albums;
SELECT band_id, COUNT(band_id) FROM albums GROUP BY band_id;
SELECT B.name AS band_name, COUNT(A.ID) AS number_of_albums FROM bands AS B LEFT JOIN albums AS A ON B.ID = A.band_id GROUP BY B.ID;
SELECT B.name AS band_name, COUNT(A.ID) AS number_of_albums FROM bands AS B LEFT JOIN albums AS A ON B.ID = A.band_id GROUP BY B.ID HAVING number_of_albums = 1;
SELECT B.name AS band_name, COUNT(A.ID) AS number_of_albums FROM bands AS B LEFT JOIN albums AS A ON B.ID = A.band_id WHERE B.name = 'Deuce' GROUP BY B.ID HAVING number_of_albums = 1;
